---
# tasks file for docker

- name: copy docker.repo
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
    owner: root
    group: root
    mode: 0644

- name: install docker-engine
  yum: name=docker-engine state=present

- name: start and enable docker service
  service: name=docker state=started enabled=yes
